# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/stable/standalone/v1alpha1application.json

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    sources:
      - repoURL: https://helm.openwebui.com/
        chart: open-webui
        targetRevision: 8.14.0
        helm:
          releaseName: open-webui
      - repoURL: https://github.com/nkaewam/homelab-gitops.git
        targetRevision: main
        ref: values
    helm:
      valueFiles:
        - $values/apps/system/open-webui/values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-webui
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
