# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/stable/standalone/v1alpha1application.json

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com/
    targetRevision: 8.14.0
    helm:
      releaseName: open-webui
      valueFiles:
        - templates/values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-webui
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
