apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-n8n-secrets
  namespace: infisical
spec:
  hostAPI: https://infisical.nkaewam.local/api
  resyncInterval: 10
  tls:
    caRef:
      secretName: homelab-root-ca-secret
      secretNamespace: cert-manager
      key: ca.crt
  authentication:
    kubernetesAuth:
      identityId: 06fce5cc-a6de-4c37-8ce3-ac28cbcf6b50
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: infisical
  
      secretsScope:
        projectId: 29795cdc-fc0d-4575-9944-0a89c24368c5
        envSlug: prod
        secretsPath: /


  managedKubeSecretReferences:
    - secretName: n8n-prod
      secretNamespace: n8n
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true