# yaml-language-server: $schema=https://raw.githubusercontent.com/KevinNitroG/argocd-json-schema/refs/heads/main/schemas/stable/standalone/v1alpha1application.json

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    chart: uptime-kuma
    repoURL: https://helm.irsigler.cloud
    targetRevision: 2.22.0
    helm:
      releaseName: uptime-kuma
      valueFiles:
        - templates/values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
